language: c
cache:
  directories:
    - $HOME/.opam
before_cache:
  - rm -rf $HOME/.opam/log
script:
  - opam init -y
  - eval `opam config env`
  - opam pin add bap git://github.com/maurer/bap#stable -y
  - opam install -y oasis
  - oasis setup
  - make check
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - camlp4
    - camlp4-extra
    - clang
    - curl
    - libcurl4-gnutls-dev
    - libgmp-dev
    - libssl-dev
    - realpath
    - libzip-dev
    - llvm
    - llvm-3.4-dev
    - m4
    - ocaml
    - ocaml-base
    - ocaml-base-nox
    - ocaml-compiler-libs
    - ocaml-native-compilers
    - ocaml-nox
    - time
    - opam
    - aspcud
    - dejagnu
    - elfutils
